"""
dashboard_yaml.py -- Peak Guard
Compacte card-YAML voor eenvoudige installatie.
"""

COMPACT_CARD_YAML = (
    "type: vertical-stack\n"
    "cards:\n"
    "\n"
    "  # Overzicht huidige maand\n"
    "  - type: markdown\n"
    "    content: >\n"
    "      ## Peak Guard -- {{ now().strftime('%B %Y') }}\n"
    "\n"
    "      | | Deze maand | Dit jaar |\n"
    "      |---|---|---|\n"
    "      | **Piekbeperking** |"
    " {{ states('sensor.peak_guard_peak_avoided_kw_this_month') }} kW"
    "  EUR {{ states('sensor.peak_guard_peak_savings_euro_this_month')"
    " | float(0) | round(2) }} |"
    " EUR {{ states('sensor.peak_guard_peak_savings_euro_this_year')"
    " | float(0) | round(2) }} |\n"
    "      | **Injectiepreventie** |"
    " {{ states('sensor.peak_guard_solar_verschoven_kwh_this_month') }} kWh"
    "  EUR {{ states('sensor.peak_guard_solar_savings_euro_this_month')"
    " | float(0) | round(2) }} |"
    " EUR {{ states('sensor.peak_guard_solar_savings_euro_this_year')"
    " | float(0) | round(2) }} |\n"
    "      | **Totaal bespaard** |"
    " EUR {{ ((states('sensor.peak_guard_peak_savings_euro_this_month') | float(0))"
    " + (states('sensor.peak_guard_solar_savings_euro_this_month') | float(0)))"
    " | round(2) }} |"
    " EUR {{ ((states('sensor.peak_guard_peak_savings_euro_this_year') | float(0))"
    " + (states('sensor.peak_guard_solar_savings_euro_this_year') | float(0)))"
    " | round(2) }} |\n"
    "\n"
    "  # Piek + capaciteit snelle metrics\n"
    "  - type: glance\n"
    "    title: Piekbeperking\n"
    "    entities:\n"
    "      - entity: sensor.peak_guard_monthly_peak_kw\n"
    "        name: Maandpiek\n"
    "      - entity: sensor.peak_guard_hypothetical_monthly_peak_kw\n"
    "        name: Zonder PG\n"
    "      - entity: sensor.peak_guard_billed_peak_kw\n"
    "        name: Aangerekend\n"
    "      - entity: sensor.peak_guard_monthly_capacity_cost_euro\n"
    "        name: Kost/maand\n"
    "\n"
    "  # Statistieken per maand - piek (geen HACS nodig)\n"
    "  - type: statistics-graph\n"
    "    title: Vermeden piek en besparing per maand\n"
    "    period: month\n"
    "    days_to_show: 365\n"
    "    stat_types:\n"
    "      - max\n"
    "    entities:\n"
    "      - entity: sensor.peak_guard_peak_avoided_kw_this_month\n"
    "        name: Vermeden kW\n"
    "      - entity: sensor.peak_guard_peak_savings_euro_this_month\n"
    "        name: Besparing EUR\n"
    "\n"
    "  # Statistieken per maand - solar (geen HACS nodig)\n"
    "  - type: statistics-graph\n"
    "    title: Verschoven energie en besparing per maand\n"
    "    period: month\n"
    "    days_to_show: 365\n"
    "    stat_types:\n"
    "      - max\n"
    "    entities:\n"
    "      - entity: sensor.peak_guard_solar_verschoven_kwh_this_month\n"
    "        name: Verschoven kWh\n"
    "      - entity: sensor.peak_guard_solar_savings_euro_this_month\n"
    "        name: Besparing EUR\n"
    "\n"
    "  # Recente piek-events\n"
    "  - type: markdown\n"
    "    title: Recente piek-events\n"
    "    content: >\n"
    "      {% set ev = state_attr('sensor.peak_guard_peak_avoided_events','events') or [] %}\n"
    "      {% if ev %}\n"
    "      | Tijdstip | Apparaat | Duur | Vermeden | Besparing |\n"
    "      |---|---|---|---|---|\n"
    "      {% for e in ev[:8] %}\n"
    "      | {{ e.timestamp_start_uitstel[:16]|replace('T',' ') }}"
    " | {{ e.apparaat }}"
    " | {{ e.gemeten_duur_min }} min"
    " | {{ e.vermeden_piek_kw }} kW"
    " | EUR {{ e.besparing_eur }} |\n"
    "      {% endfor %}\n"
    "      {% else %}\n"
    "      Nog geen piek-events deze maand.\n"
    "      {% endif %}\n"
    "\n"
    "  # Recente solar-events\n"
    "  - type: markdown\n"
    "    title: Recente solar-events\n"
    "    content: >\n"
    "      {% set ev = state_attr('sensor.peak_guard_solar_avoided_events','events') or [] %}\n"
    "      {% if ev %}\n"
    "      | Tijdstip | Apparaat | Duur | Verschoven | Besparing |\n"
    "      |---|---|---|---|---|\n"
    "      {% for e in ev[:8] %}\n"
    "      | {{ e.timestamp_start_inschakeling[:16]|replace('T',' ') }}"
    " | {{ e.apparaat }}"
    " | {{ e.gemeten_duur_min }} min"
    " | {{ e.verschoven_kwh }} kWh"
    " | EUR {{ e.besparing_eur }} |\n"
    "      {% endfor %}\n"
    "      {% else %}\n"
    "      Nog geen solar-events deze maand.\n"
    "      {% endif %}\n"
)